import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Card from '@/components/card'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  fetch("https://rickandmortyapi.com/api/character/259")
          .then(response => console.log("Se cumplio la promesa: " + response))
          .catch(reason => console.log("No cumplida: " + reason))

 const myData = [ {name:"Pencilvester", image:"https://rickandmortyapi.com/api/character/avatar/259.jpeg"  },
 {name:"Orthodox Jew", image:"https://rickandmortyapi.com/api/character/avatar/255.jpeg"  }]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Hola mundo
        {
          myData.map(element => (<Card image={element.image} name={element.name}></Card>))
        }
      </main>
    </>
  )
}
