import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Card from '@/components/card'
import data from 'public/data.json'
import myJsArray from '@/components/converter'
import Clock from '@/components/Clock'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  fetch("https://rickandmortyapi.com/api/character/259")
          .then(response => console.log("Se cumplio la promesa: " + response))
          .catch(reason => console.log("No cumplida: " + reason))
//console.log(data)
  //const myJsArray = Array.from(JSON.parse(data));
 //const myData = myJsArray;
 var myData = [];
for(var i in data) {
    if( !isNaN(+i)) {
        myData[+i] = data[i];
    }
}
console.log(myData.length)

//  [ {name:"Pencilvester", image:"https://rickandmortyapi.com/api/character/avatar/259.jpeg"  },
//  {name:"Orthodox Jew", image:"https://rickandmortyapi.com/api/character/avatar/255.jpeg"  }]
  return (
    <>
      <Head>
        <title>Proyecto 001</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Hola mundo
        <Clock className={styles.reloj}></Clock>
        {
          myData.map(element => (<Card image={element.image} name={element.name}></Card>))
        }
        <Clock date={new Date()}></Clock>
      </main>
    </>
  )
}
