import InitialLogin from "@/components/login/initialLogin";
import ContextProvider from "@/context/contextprovider";
import Head from 'next/head'
import { Inter } from 'next/font/google'

import styles from '@/styles/Home.module.css'
import Card from '@/components/card'
import data from 'public/data.json'
import myJsArray from '@/components/converter'
import Clock from '@/components/Clock'

const inter = Inter({ subsets: ['latin'] })

export default function test(){
    return(
       <>
       <Head>
          <title>Component Test</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <ContextProvider>
            <InitialLogin/>
        </ContextProvider>

       </>
    )
}